"""
Integration tests: the real feature-extraction pipeline on real (synthesized)
video files — catches wiring breaks that unit tests on pure functions miss.

Videos are generated at test time with the bundled/system ffmpeg; tests skip
cleanly when no encoder is available.
"""
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))


def _ffmpeg() -> str | None:
    exe = shutil.which("ffmpeg")
    if exe:
        return exe
    try:
        import imageio_ffmpeg
        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return None


FFMPEG = _ffmpeg()
pytestmark = pytest.mark.skipif(FFMPEG is None, reason="no ffmpeg available")


@pytest.fixture(scope="module")
def clean_video():
    """3s synthetic clip with no special metadata — should read as real."""
    path = os.path.join(tempfile.mkdtemp(), "clean.mp4")
    subprocess.run(
        [FFMPEG, "-y", "-f", "lavfi", "-i", "testsrc2=size=320x240:rate=24:duration=3",
         "-pix_fmt", "yuv420p", path],
        check=True, capture_output=True,
    )
    return path


@pytest.fixture(scope="module")
def sora_tagged_video(clean_video):
    """Same clip re-muxed with Sora-style metadata — must be flagged as AI."""
    path = os.path.join(tempfile.mkdtemp(), "sora.mp4")
    subprocess.run(
        [FFMPEG, "-y", "-i", clean_video, "-c", "copy",
         "-metadata", "encoder=Sora",
         "-metadata", "comment=Generated by OpenAI Sora", path],
        check=True, capture_output=True,
    )
    return path


def test_clean_video_reads_as_real(clean_video):
    from analyzer import extract_features
    result = extract_features(clean_video)
    assert result.verdict != "ai_generated"
    assert result.confidence < 0.5
    assert len(result.feature_vector) > 30


def test_sora_metadata_flags_ai(sora_tagged_video):
    from analyzer import extract_features
    result = extract_features(sora_tagged_video)
    assert result.verdict == "ai_generated"
    assert result.confidence >= 0.9
    assert result.ai_tool and "sora" in result.ai_tool.lower()


def test_feature_vector_is_stable_order(clean_video, sora_tagged_video):
    """The ML model depends on a fixed feature order — vectors must align."""
    from analyzer import extract_features
    a = extract_features(clean_video).feature_vector
    b = extract_features(sora_tagged_video).feature_vector
    assert len(a) == len(b)
    assert all(isinstance(v, (int, float)) for v in a + b)


def test_classifier_predicts_on_real_vector(clean_video):
    from analyzer import extract_features
    from models.classifier import get_classifier
    vec = extract_features(clean_video).feature_vector
    prob, is_ai = get_classifier().predict(vec)
    if prob is not None:  # model artifact present
        assert 0.0 <= prob <= 1.0


def test_run_full_analysis_shape(sora_tagged_video):
    """The server pipeline returns the full contract incl. explanation."""
    from api.server import run_full_analysis
    res = run_full_analysis(sora_tagged_video, deep=False)
    for field in ("verdict", "confidence", "detection_method", "explanation", "_signals"):
        assert field in res, f"missing field: {field}"
    exp = res["explanation"]
    assert "provenance" in exp and "layer_scores" in exp
    assert res["verdict"] == "ai_generated"
    assert exp["provenance"]["ai_tool"]
