"""
Tests for the code-first fast path (run_fast_analysis / extract_features
code_only). This path is what Telegram, WhatsApp and /detect?mode=fast rely
on, so its verdict and speed guarantees get pinned here.
"""
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))


def _ffmpeg():
    exe = shutil.which("ffmpeg")
    if exe:
        return exe
    try:
        import imageio_ffmpeg
        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return None


FFMPEG = _ffmpeg()
pytestmark = pytest.mark.skipif(FFMPEG is None, reason="no ffmpeg available")


@pytest.fixture(scope="module")
def clean_video(tmp_path_factory):
    d = tmp_path_factory.mktemp("fast")
    p = d / "clean.mp4"
    subprocess.run([FFMPEG, "-y", "-f", "lavfi", "-i",
                    "testsrc2=size=240x180:rate=15:duration=2.5",
                    "-pix_fmt", "yuv420p", str(p)], check=True, capture_output=True)
    return str(p)


@pytest.fixture(scope="module")
def sora_video(clean_video, tmp_path_factory):
    d = tmp_path_factory.mktemp("fast_ai")
    p = d / "sora.mp4"
    subprocess.run([FFMPEG, "-y", "-i", clean_video, "-c", "copy",
                    "-metadata", "comment=Generated by OpenAI Sora", str(p)],
                   check=True, capture_output=True)
    return str(p)


def test_code_only_skips_frame_decoding(clean_video):
    from analyzer import extract_features
    r = extract_features(clean_video, code_only=True)
    # deep signals must NOT have run in code-only mode
    assert not r.signals.get("freq_analyzed")
    assert not r.signals.get("visual_analyzed")


def test_fast_flags_sora_from_metadata(sora_video):
    from api.server import run_fast_analysis
    res = run_fast_analysis(sora_video)
    assert res["verdict"] == "ai_generated"
    assert res["confidence"] >= 0.9
    assert res["mode"] == "fast"
    assert res["ai_tool_detected"] and "sora" in res["ai_tool_detected"].lower()
    assert res["explanation"]["provenance"]["ai_tool"]


def test_fast_is_quick(sora_video):
    from api.server import run_fast_analysis
    t0 = time.time()
    run_fast_analysis(sora_video)
    assert time.time() - t0 < 5.0  # code path must be fast, no frame decode


def test_fast_platform_flag_is_definitive(clean_video):
    from api.server import run_fast_analysis
    res = run_fast_analysis(clean_video, platform_flag={"flagged": True, "info": "TikTok AIGC"})
    assert res["verdict"] == "ai_generated"
    assert res["confidence"] >= 0.9
    assert res["explanation"]["provenance"]["platform_ai_label"] is True


def test_fast_clean_video_not_flagged(clean_video):
    from api.server import run_fast_analysis
    res = run_fast_analysis(clean_video)
    # a plain clip with no AI evidence must not be called AI on the fast path
    assert res["verdict"] != "ai_generated"
    assert res["mode"] == "fast"
