"""Metadata reader edge cases — especially the probe-failure guard.

A transient ffprobe failure must never masquerade as "metadata stripped"
(which the pipeline treats as a lean toward REAL).
"""
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

import analyzer.metadata_reader as mr


def _ffmpeg():
    exe = shutil.which("ffmpeg")
    if exe:
        return exe
    try:
        import imageio_ffmpeg
        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return None


FFMPEG = _ffmpeg()
pytestmark = pytest.mark.skipif(FFMPEG is None, reason="no ffmpeg available")


@pytest.fixture(scope="module")
def tagged_video():
    d = tempfile.mkdtemp()
    clean = f"{d}/clean.mp4"
    tagged = f"{d}/tagged.mp4"
    subprocess.run([FFMPEG, "-y", "-f", "lavfi", "-i", "testsrc2=size=160x120:rate=12:duration=2.5",
                    "-pix_fmt", "yuv420p", clean], check=True, capture_output=True)
    # NOTE: ffmpeg overwrites the 'encoder' tag with its own Lavf version on
    # remux — the surviving marker is the comment tag, like real Sora exports.
    subprocess.run([FFMPEG, "-y", "-i", clean, "-c", "copy",
                    "-metadata", "encoder=Sora",
                    "-metadata", "comment=Generated by OpenAI Sora", tagged],
                   check=True, capture_output=True)
    return tagged


def test_probe_failure_is_not_stripped_metadata(tagged_video, monkeypatch):
    monkeypatch.setattr(mr, "FFPROBE", "/nonexistent/ffprobe")
    m = mr.read_metadata(tagged_video)
    assert m.probe_failed is True
    assert m.metadata_is_stripped is False   # we couldn't look — emptiness is not evidence
    assert m.ai_tool_detected in (None, False, "") or not m.ai_tool_detected


def test_normal_probe_reads_ai_tool(tagged_video):
    m = mr.read_metadata(tagged_video)
    assert m.probe_failed is False
    assert m.ai_tool_detected
    assert "sora" in (m.ai_tool_detected or "").lower()
