"""
Vision-based AI video detection using Claude claude-haiku-4-5.
Extracts frames from the video and analyzes them visually for AI generation artifacts.
Works even when platform re-encoding (TikTok/Instagram) strips all metadata.
"""
import os
import base64
import subprocess
import tempfile
import shutil
from pathlib import Path
from typing import Optional
from dataclasses import dataclass

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False


@dataclass
class VisionResult:
    is_ai: bool
    confidence: float
    verdict: str          # "ai_generated" | "ai_edited" | "real" | "unknown"
    reasoning: str
    frames_analyzed: int


VISION_PROMPT = """You are an expert forensic analyst specializing in detecting AI-generated videos.

Analyze these video frames and determine if the video was generated by an AI tool (like Sora, Kling, Runway, Pika, Luma, HeyGen, etc.) or if it shows real footage captured by a camera.

Look for these AI generation artifacts:
- Unnaturally smooth or plastic-looking skin textures
- Background elements that morph, blur, or distort inconsistently
- Hands/fingers with wrong number or impossible geometry
- Text that's garbled, morphed, or unreadable
- Eyes that look glassy, too symmetric, or unnaturally bright
- Lighting that doesn't follow physics (inconsistent shadows, impossible reflections)
- Hair that behaves like liquid or blends into background
- Temporal inconsistencies (objects appearing/disappearing)
- Over-smooth motion with no natural camera shake or micro-movements
- Backgrounds with repeated or symmetrical patterns
- Fabric/clothing with impossible folds or merging with skin
- Animals with wrong anatomy or extra limbs

Also look for AI EDITING artifacts (real footage + AI effects):
- Face swaps or face replacements (HeyGen, D-ID)
- AI-generated backgrounds replacing real ones
- AI-enhanced facial features (beauty filters at extreme levels)
- AI-generated text overlays or graphics

Respond in this exact JSON format:
{
  "verdict": "ai_generated" | "ai_edited" | "real",
  "confidence": 0.0-1.0,
  "reasoning": "Brief explanation of key visual evidence (max 100 chars)",
  "key_artifacts": ["artifact1", "artifact2"]
}

Be conservative — only say ai_generated if you see CLEAR evidence. Real videos can have compression artifacts that look unusual. When in doubt, say real."""


def extract_frames(video_path: str, n_frames: int = 6) -> list[str]:
    """Extract n evenly-spaced frames from video as base64 JPEG."""
    ffmpeg = shutil.which("ffmpeg") or "ffmpeg"
    tmp_dir = tempfile.mkdtemp()
    frames = []

    try:
        # Get video duration
        probe = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json",
             "-show_format", video_path],
            capture_output=True, text=True, timeout=10
        )
        import json
        data = json.loads(probe.stdout)
        duration = float(data.get("format", {}).get("duration", 5))

        # Extract frames at even intervals
        for i in range(n_frames):
            t = duration * (i + 0.5) / n_frames
            out = os.path.join(tmp_dir, f"frame_{i:02d}.jpg")
            r = subprocess.run(
                [ffmpeg, "-ss", str(t), "-i", video_path,
                 "-vframes", "1", "-q:v", "3",
                 "-vf", "scale=512:-1",
                 out, "-y", "-loglevel", "error"],
                capture_output=True, timeout=15
            )
            if r.returncode == 0 and os.path.exists(out):
                with open(out, "rb") as f:
                    frames.append(base64.standard_b64encode(f.read()).decode())

    except Exception:
        pass
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    return frames


def analyze_with_vision(video_path: str) -> Optional[VisionResult]:
    """Analyze video frames with Claude claude-haiku-4-5 vision."""
    if not ANTHROPIC_AVAILABLE:
        return None

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    frames = extract_frames(video_path, n_frames=6)
    if not frames:
        return None

    try:
        client = anthropic.Anthropic(api_key=api_key)

        # Build message with all frames
        content = []
        for i, frame_b64 in enumerate(frames):
            content.append({
                "type": "text",
                "text": f"Frame {i+1}/{len(frames)}:"
            })
            content.append({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/jpeg",
                    "data": frame_b64,
                }
            })
        content.append({"type": "text", "text": VISION_PROMPT})

        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=256,
            messages=[{"role": "user", "content": content}]
        )

        import json, re
        text = response.content[0].text.strip()
        # Extract JSON from response
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if not match:
            return None

        data = json.loads(match.group())
        verdict = data.get("verdict", "real")
        confidence = float(data.get("confidence", 0.5))
        reasoning = data.get("reasoning", "")

        return VisionResult(
            is_ai=verdict == "ai_generated",
            confidence=confidence,
            verdict=verdict,
            reasoning=reasoning,
            frames_analyzed=len(frames),
        )

    except Exception as e:
        return None
